1. data creation : create a suitable arrays to represent students,subjects,amd their marks


In [ ]:
impor],[66,89,41,98],[76,80,67,95]])
sclt numpy as np
scl = np.array([[83,90,79,87

array([[83, 90, 79, 87],
       [66, 89, 41, 98],
       [76, 80, 67, 95]])

2. data exploration: explore the properties of these arrays ,such as their dimensions,size,and structure



In [ ]:
scl.shape
scl.ndim
scl.size

12

3. data transformation : perform necessary reshaping and regognising of the data to suit various operations.



In [ ]:
scl.T

array([[83, 66, 76],
       [90, 89, 80],
       [79, 41, 67],
       [87, 98, 95]])

4. Data combination: merge or split arrays to stimulate adding new students ,new subjects,or recognaising the datasets

In [ ]:
newcol = np.array([[87],[45],[98]])
scl = np.hstack((scl,newcol))
scl

array([[83, 90, 79, 87, 87],
       [66, 89, 41, 98, 45],
       [76, 80, 67, 95, 98]])

5.data modification: apply operations to update marks,remove data,or identify unique information

In [ ]:
student = scl[0]
subject = scl[1]
marks = scl[2]

marks[0]=87
marks[3]=76.4

np.delete(subject,4)

subject

marks




array([87, 80, 67, 76, 98])

6.data type handling: demonstrate how the same data can exist in different,data types and how changes affect results

In [ ]:
data = np.array([student,subject,marks])
data

array([[83, 90, 79, 87, 87],
       [66, 89, 41, 98, 45],
       [87, 80, 67, 76, 98]])

7.copy and view behaviour: show the difference between creating a full copy of an array and creating a view of the same data.

In [ ]:
nscl=scl.copy()
nscl[0][4]=108
nscl
'''array([[ 81,  82,  83,  84,  85,  86,  87],
       [87, 67, 56, 78, 90, 97, 99],
       [  71,   76,   88,   57,   46,   93,   47]])'''
scl
'''array([[ 11,  12,  13,  14,  17,  18,  19],
       [65, 76, 35,54, 98, 97, 87],
       [  98,   55,   44,   33,   22,   87,   98]])'''

scl



array([[83, 90, 79, 87, 87],
       [66, 89, 41, 98, 45],
       [87, 80, 67, 76, 98]])

In [ ]:
vscl = scl.view()
vscl[1][4]=8978
vscl
'''array([[ 81,  82,  83,  84,  85,  86,  87],
       [87, 67, 56, 78, 90, 97, 99],
       [  71,   76,   88,   57,   46,   93,   47]])'''
scl
'''array([[ 11,  12,  13,  14,  17,  18,  19],
       [65, 76, 35,54, 98, 97, 87],
       [  98,   55,   44,   33,   22,   87,   98]])'''
scl

array([[  83,   90,   79,   87,   87],
       [  66,   89,   41,   98, 8978],
       [  87,   80,   67,   76,   98]])